import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/bash"
args = ["-l"]

[env]
TERM = "xterm-256color" 

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
size = 18.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
